name: Build & Release

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  workflow_dispatch:
permissions:
  contents: write

jobs:
  context:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set.outputs.version }}
      is_tag: ${{ steps.set.outputs.is_tag }}

    steps:
      - id: set
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
              VERSION="${GITHUB_REF#refs/tags/v}"
              echo "env_name=production" >> $GITHUB_OUTPUT
              echo "version=$VERSION" >> $GITHUB_OUTPUT
              echo "is_tag=true" >> $GITHUB_OUTPUT
          else
              if [[ "${GITHUB_REF_NAME}" == "main" ]]; then
              echo "env_name=production" >> $GITHUB_OUTPUT
              else
              echo "env_name=stage" >> $GITHUB_OUTPUT
              fi
              echo "version=0.0.0" >> $GITHUB_OUTPUT
              echo "is_tag=false" >> $GITHUB_OUTPUT
          fi

  generate-onnx-models:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Python dependencies
        run: |
          pip install ultralytics fast-plate-ocr 'fast-plate-ocr[onnx]' huggingface_hub

      - name: Export models
        run: python export_models.py

      - name: Upload models
        uses: actions/upload-artifact@v4
        with:
          name: models
          path: models/

  build-linux:
    needs: [generate-onnx-models, context]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download models
        uses: actions/download-artifact@v4
        with:
          name: models
          path: models/

      - name: Build
        run: ./build.sh

      - name: Generate Package
        run: |
          OUT_DIR=dist/lpr-sdk
          mkdir -p $OUT_DIR/include
          mkdir -p $OUT_DIR/lib
          mkdir output

          cp -r include/* $OUT_DIR/include/
          cp build/liblpr_sdk_static.a $OUT_DIR/lib/
          cp build/liblpr_sdk_shared.so $OUT_DIR/lib/
          cp build/open_lpr $OUT_DIR/lib/
          cp third_party/onnxruntime/linux/libonnxruntime.so.1.23.2 $OUT_DIR/lib/

          if [[ "${{ needs.context.outputs.is_tag }}" == "true" ]]; then
            tar -czf output/open-lpr-sdk-linux-x64-${{ needs.context.outputs.version }}.tgz -C dist lpr-sdk
          else
            tar -czf output/open-lpr-sdk-linux-x64-0.0.0.tgz -C dist lpr-sdk
          fi

      - uses: actions/upload-artifact@v4
        with:
          name: linux-x64
          path: output/

  build-android:
    needs: [generate-onnx-models, context]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download models
        uses: actions/download-artifact@v4
        with:
          name: models
          path: models/

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install NDK
        run: |
          sdkmanager "ndk;26.1.10909125"

      - name: Set NDK env
        run: echo "ANDROID_NDK=$ANDROID_SDK_ROOT/ndk/26.1.10909125" >> $GITHUB_ENV

      - name: Build
        run: ./build-android.sh

      - name: Generate Package
        run: |
          mkdir output

          if [[ "${{ needs.context.outputs.is_tag }}" == "true" ]]; then
            cp android/openlprsdk/build/outputs/aar/openlprsdk-release.aar output/open-lpr-sdk-android-${{ needs.context.outputs.version }}.aar
          else
            cp android/openlprsdk/build/outputs/aar/openlprsdk-release.aar output/open-lpr-sdk-android-0.0.0.aar
          fi

      - uses: actions/upload-artifact@v4
        with:
          name: android-aar
          path: output/

  build-osx:
    needs: [generate-onnx-models, context]
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download models
        uses: actions/download-artifact@v4
        with:
          name: models
          path: models/

      - name: Build
        run: ./build.sh

      - name: Generate Package
        run: |
          OUT_DIR=dist/lpr-sdk
          mkdir -p $OUT_DIR/include
          mkdir -p $OUT_DIR/lib
          mkdir output

          cp -r include/* $OUT_DIR/include/
          cp build/liblpr_sdk_static.a $OUT_DIR/lib/
          cp build/liblpr_sdk_shared.dylib $OUT_DIR/lib/
          cp build/open_lpr $OUT_DIR/lib/
          cp third_party/onnxruntime/macos/libonnxruntime.1.23.2.dylib $OUT_DIR/lib/

          if [[ "${{ needs.context.outputs.is_tag }}" == "true" ]]; then
            tar -czf output/open-lpr-sdk-osx-arm64-${{ needs.context.outputs.version }}.tgz -C dist lpr-sdk
          else
            tar -czf output/open-lpr-sdk-osx-arm64-0.0.0.tgz -C dist lpr-sdk
          fi

      - uses: actions/upload-artifact@v4
        with:
          name: osx-arm64
          path: output/

  build-ios:
    needs: [generate-onnx-models, context]
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download models
        uses: actions/download-artifact@v4
        with:
          name: models
          path: models/

      - name: Build
        run: ./build-ios.sh

      - name: Generate Package
        run: |
          mkdir -p output
          cd build-ios
          zip -r ../output/LprSdk.xcframework.zip LprSdk.xcframework
          swift package compute-checksum ../output/LprSdk.xcframework.zip > checksum.txt
          echo "CHECKSUM=$(cat checksum.txt)" >> $GITHUB_OUTPUT

      - uses: actions/upload-artifact@v4
        with:
          name: ios-arm64
          path: output/

  release:
    needs: [build-linux, build-android, build-osx, build-ios, context]
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Generate name
        id: meta
        run: |
          if [[ "${{ needs.context.outputs.is_tag }}" == "true" ]]; then
              echo "name=Release v${{ needs.context.outputs.version }}" >> $GITHUB_OUTPUT
              echo "tag=v${{ needs.context.outputs.version }}" >> $GITHUB_OUTPUT
              echo "prerelease=false" >> $GITHUB_OUTPUT
          else
              echo "name=Build 0.0.0 (#${GITHUB_RUN_NUMBER})" >> $GITHUB_OUTPUT
              echo "tag=build-${GITHUB_RUN_NUMBER}" >> $GITHUB_OUTPUT
              echo "prerelease=true" >> $GITHUB_OUTPUT
          fi

      - name: Create Release + Upload Assets
        id: release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.meta.outputs.tag }}
          name: ${{ steps.meta.outputs.name }}
          prerelease: ${{ steps.meta.outputs.prerelease }}
          files: |
            artifacts/**/*.tgz
            artifacts/**/*.zip
            artifacts/**/*.aar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
